name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Registry
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        IMAGE_TAG=$GITHUB_REPOSITORY/application:${GITHUB_SHA::8}
        docker build --pull -t $IMAGE_TAG .
        docker push $IMAGE_TAG

  unit-test-job:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Unit Tests
      run: |
        echo "Running unit tests... This will take about 60 seconds."
        sleep 60
        echo "Code coverage is 90%"

  trigger-job:
    runs-on: ubuntu-latest
    needs: unit-test-job

    steps:
    - name: Trigger Downstream Pipeline
      uses: appleboy/trigger-pipeline@v1
      with:
        repo: project
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: main
        variables: '{"IMAGE_TAG": "${{ needs.docker-build.outputs.IMAGE_TAG }}"}'
